### ISSUE TITLE
continuum_imaging.py dirty image 

### ISSUE THREAD

**Issue by AndresErnestoGuzman** [ALMA-IMF/reduction#110]
@keflavich 

Hi Adam,
https://github.com/ALMA-IMF/reduction/blob/9f55a5c0ddd19f31ef091dc6c77c71759108ef80/reduction/continuum_imaging.py#L236

I think there is a problem in this tclean call. The  dirty_impars dictionary has a `"usemask":"user"` entry, which conflicts the explicit `usemask='pb'` we give in the tclean call.  I recommend to put 
`dirty_impars['usemask'] = 'pb'` before  `tclean(... `and delete `usemask='pb'`  it from inside tclean.

**Comment by keflavich** [comment]
Masks have no effect on the dirty image one way or another, so this won't affect anything about the image.  It would be better to be self-consistent, though.

**Comment by AndresErnestoGuzman** [comment]
I meant, the tclean failed with this error
![image](https://user-images.githubusercontent.com/55287447/99604413-c9684d80-2a48-11eb-9746-b2ff94fbaa8a.png)

**Comment by keflavich** [comment]
I see, that's definitely a problem.

**Comment by keflavich** [comment]
oh, you're generally not supposed to use `continuum_imaging.py` any more; instead use `continuum_imaging_selfcal.py`

**Comment by keflavich** [comment]
I've pushed a fix and deprecated continuum_imaging.py
