### ISSUE TITLE
Expanding SiO cubes for selected fields

### ISSUE THREAD

**Issue by apmtowner** [ALMA-IMF/reduction#164]
Task: expand SiO-only cubes so that they have the same velocity extent as CO. Seven cubes will be reimaged through the pipeline, but for the seven cubes in this issue we will use an alternate method.

Method: attempting to "expand" the cubes by taking cutouts from the B6 spw1 fullcubes, rather than re-imaging SiO-only. In theory this should be faster.

Velocity ranges: the vlsr and velocity ranges below are calculated using the rest frequency of SiO 5-4 as the reference frequency - 217.104984 GHz. All vlsr and cubewidth values can also be found in the 'line_parameters_custom' dictionary in reduction/imaging_parameters.py.

Fields:
   G008: vlsr = 35 km/s, cubewidth = 150 km/s, so vmin = -40 km/s, vmax = 110 km/s
   G010: vlsr =  -2 km/s, cubewidth = 150 km/s, so vmin = -77 km/s, vmax = 73 km/s
   G012: vlsr = 35.5 km/s, cubewidth = 150 km/s, so vmin = -39.5 km/s, vmax = 110.5 km/s
   G333: vlsr = -48 km/s, cubewidth = 150 km/s, so vmin = -123 km/s, vmax = 27 km/s
   G337: vlsr = -39 km/s, cubewidth = 150 km/s, so vmin = -114 km/s, vmax = 36 km/s
   G353: vlsr = -18 km/s, cubewidth = 150 km/s, so vmin = -93 km/s, vmax = 57 km/s
   W51-IRS2: vlsr = 60 km/s, cubewidth = 150 km/s, so vmin = -15 km/s, vmax = 135 km/s

**Comment by keflavich** [comment]
@cunninghamnichol This means we can consider these fields done and just distribute slices of the existing full cubes.

**Comment by keflavich** [comment]
solved by https://github.com/ALMA-IMF/reduction/commit/e6b26b9525717528f5029a4b9b04b0df26d27264

**Comment by keflavich** [comment]
#160

**Comment by keflavich** [comment]
Reruns are going as of 12/3/2021
