### ISSUE TITLE
Add rescaling code for dirty beam

### ISSUE THREAD

**Issue by keflavich** [ALMA-IMF/reduction#168]
We need rescaling code that will do:

```
def rescale(model, residual, psf):
    epsilon = get_epsilon_from_psf(psf)
    synthbeam = get_synthbeams(psf)
    convmodel = convolve(model, synthbeam)
    restored = residual * epsilon + convmodel
    return restored
```

the `get_epsilon_from_psf` is just a subset of `get_psf_secondpeak` or @rgalvanmadrid 's residual fix code.

`get_synthbeams` and `convolve_model` can be done with some CASA code or, better, with spectral-cube:
```python
beams = SpectralCube.read(psf).beams
convmodel = SpectralCube.read(model).convolve(beams)
```
but that won't quite work I think b/c the model is beamless....

I'll work on turning this pseudocode into code later.

**Comment by rgalvanmadrid** [comment]
The model is beamless but it has the same geometry as the residual and psf cubes, so I guess one could just convolve each channel of the model with the respective clean beam stored in the psf header? 
That's how it's done for a single test channel in  `residuals_fix.py`, and I checked manually that the photometry in the recalculated restored channel is the same as the CASA-produced one.

**Comment by keflavich** [comment]
Code we're talking about here:
https://github.com/ALMA-IMF/reduction/blob/master/misc/residuals_fix.py

https://github.com/ALMA-IMF/reduction/blob/master/analysis/imstats.py#L41-L205

**Comment by keflavich** [comment]
https://github.com/radio-astro-tools/spectral-cube/issues/766

**Comment by keflavich** [comment]
ok the model convolution step is kind of easy.  We want to convolve to a commonbeam anyway, so:

```python
psf = SpectralCube.read(psf_filename, format='casa_image')
commonbeam = psf.beams.common_beam()
DeltaBeam = radio_beam.Beam(0)
modelcube = SpectralCube.read(modelcube, format='casa_image').with_beam(DeltaBeam)
sm_modcube = modelcube.convolve_to(commonbeam)
```

**Comment by rgalvanmadrid** [comment]
Working version. I'm sure you will want to change a few things: 
https://github.com/ALMA-IMF/reduction/commit/9d3846ff08e80a8c1fe1771d4ff87c3c628ead78

**Comment by rgalvanmadrid** [comment]
First corrections: 
https://github.com/ALMA-IMF/reduction/commit/424a804da3d7df68abab26f3132cbd392ae7d497

**Comment by keflavich** [comment]
This has all been merged.  Ideally we'll make a generalized version in https://github.com/radio-astro-tools/beam-volume-tools, but that's not ready yet
