### ISSUE TITLE
Correct error in continuum_imaging_selfcal.py

### ISSUE THREAD

**Issue by folguinch** [ALMA-IMF/reduction#58]
Hi Adam, in `continuum_imaging_selfcal.py` after line 176 (after checking for bsens) you should add:
```python
else:
    do_bsens = False
```
so the `do_bsens` variable is not undefined when you use it later.

**Comment by keflavich** [comment]
Thanks for seeing that.  It is now fixed - I merged a different PR (#48) that included the fix
