### ISSUE TITLE
File naming for bsens

### ISSUE THREAD

**Issue by folguinch** [ALMA-IMF/reduction#59]
In `continuum_imaging_selfcal.py`, the files in `imaging_results` have the same names with and without `do_bsens`. Should a `_bsens` be added to the `basename` variable (or other variable)?

**Comment by folguinch** [comment]
Maybe the same suffix should be added to the `reg` files, so there isn't any mix-up.

**Comment by keflavich** [comment]
hmm, yes, I thought the bsens files did have that suffix attached?  I'll have a look.

For the reg files, I had assumed that the masks would be the same...

**Comment by folguinch** [comment]
So just noticed that when it does bsens, it does both (because of the `continuum_mses += [...]`). Is this suppose to be that way?
For some reason when I ran the program it finished with a seg fault in the first ms and never reached the bsens ms.

**Comment by keflavich** [comment]
@folguinch is there still an issue here that I need to help deal with, or are things now working alright?

**Comment by folguinch** [comment]
It seems to be working alright now. I'm closing this issue.
