### ISSUE TITLE
get_mous_to_sb_mapping only identifies QA2 pass SBs

### ISSUE THREAD

**Issue by jmangum** [ALMA-IMF/reduction#68]
The mapping dictionary generated by get_mous_to_sb_mapping tests for row['QA2 status'] == 'Y', which I believe means QA2 == pass.  Some SBs are delivered as semi-pass, which do not get included in the MOUS-to-SB mapping.  This then causes make_humanreadable_links to fail to match a pipeline directory from a QA2 semi-pass SB to its associated mapping dictionary entry, leading to failure.  Fix would appear to involve allowing for row['QA2 status'] == 'N', based on what get_mous_to_sb_mapping extracts from the ALMA archive:

In [61]: run make_humanreadable_links.py                                        
    Member ous id         SB name     QA2 Status
--------------------- --------------- ----------
uid://A001/X1284/Xf3d  ngc253_d_04_7M          Y
uid://A001/X1284/Xf4f  ngc253_g_04_7M          Y
uid://A001/X1284/Xf49  ngc253_f_04_7M          Y
uid://A001/X1284/Xf43  ngc253_e_04_7M          Y
uid://A001/X1284/Xf31  ngc253_b_04_7M          Y
uid://A001/X1284/Xf2b  ngc253_a_04_7M          Y
uid://A001/X1284/Xf37  ngc253_c_04_7M          Y
                  ...             ...        ...
uid://A001/X1284/Xfe9 ngc253_p_07_TM1          Y
uid://A001/X1284/Xf5f ngc253_c_06_TM1          Y
uid://A001/X1284/Xf53 ngc253_a_06_TM1          Y
uid://A001/X1284/Xfad ngc253_f_07_TM1          Y
uid://A001/X1284/Xf65 ngc253_d_06_TM1          Y
uid://A001/X1284/Xfa1 ngc253_d_07_TM1          Y
uid://A001/X1284/Xf11 ngc253_c_03_TM1          N
Length = 78 rows

Might be more appropriate to add a parameter to get_mous_to_sb_mapping which tells it to grab semi-pass in addition to pass SBs.

Tested make_humanreadable_links by removing the row['QA2 status'] test from get_mous_to_sb_mapping.  Now grabs all pipeline logs and extracts flux information without failure.

**Comment by keflavich** [comment]
`get_mous_to_bs_mapping` accepts the parameter `QA2_required` - set that to False

**Comment by jmangum** [comment]
Looks like my version of get_mous_to_sb_mapping does not include this attribute:
In [97]: hasattr(get_mous_to_sb_mapping,'QA2_required')                         
Out[97]: False

**Comment by keflavich** [comment]
It's not an attribute, it's a keyword argument.

https://github.com/ALMA-IMF/reduction/blob/master/reduction/parse_weblog.py#L16

**Comment by jmangum** [comment]
Of course. Called from make_humanreadable_links, then:
mapping = get_mous_to_sb_mapping('2017.1.00161.L', QA2_required=False)
mapping2 = get_mous_to_sb_mapping('2018.1.00162.S', QA2_required=False)
mapping.update(mapping2)

Works perfectly.  Thanks!
