### ISSUE TITLE
make_humanreadable_links processes only one ALMA project

### ISSUE THREAD

**Issue by jmangum** [ALMA-IMF/reduction#69]
Adam already pointed this fix out to me.  If you want to process pipeline weblogs from multiple ALMA projects, where you have put all of your weblogs into a single directory (in this case, the directory associated with the ALMA project 2017.1.00161.L), make the following change to make_humanreadable_links:

mapping = get_mous_to_sb_mapping('2017.1.00161.L')
mapping2 = get_mous_to_sb_mapping('2018.1.00162.S')
mapping.update(mapping2)

It is not clear to me that this is a good idea, but it works nonetheless.

**Comment by keflavich** [comment]
Closing as this is resolved.  Thanks!

(and there are no expected problems from doing this)
